### ISSUE TITLE
CSV File needs to assign tables and conference

### ISSUE THREAD

**Issue by andrewkazura** [SCCapstone/CareerCenterApp#31]
right now it adds all the companies but doesn't add the tables or conferences. Some companies have more than 1 table though and are only in the excel file once

**Comment by finleye** [comment]
I'll add a drop-down on the import page that lets you select the conference you intend the employers to be uploaded for. I'll make sure it auto-selects the `@current_con` session token if it exists.

As far as the tables, that's a little more tricky. I'll have to look into how to go about that. Since some companies have more than one table. Since it's so rare for employers to have multiple tables, could it be a simpler solution to just display the first table? That's probably a question for @josemvidal

**Comment by finleye** [comment]
Ready for QA! :sunglasses: @andrewkazura @ballardaf

**Comment by andrewkazura** [comment]
works and looks good. ready for production @finleye

**Comment by ballardaf** [comment]
closing!
