### ISSUE TITLE
CSV File Button

### ISSUE THREAD

**Issue by ballardaf** [SCCapstone/CareerCenterApp#44]
Create a link button to upload CSV file next to new employer on all employers page or the selected conference. Also, display the selected conference in the navbar.

**Comment by andrewkazura** [comment]
where do you want me to put the conference on the navbar? 

I'm also having some trouble finding a way to display the name of the conference. Since the id is only being saved I am trying to run a loop for each of the conferences matching their id to the current_con session variable. The problem I'm having is that it says that (highlighting line 2 below):
undefined method `each' for nil:NilClass

do I need to add anything else to another page to be able to run that method? I saw this being run on the employers table and I didn't see anything that was related to that in its controller. Below is the code I am running

<% if session[:current_con] != "" %>
     <% @conferences.each do |conference| %>
           <% if conference.id == session[:current_con]%>
                <%=  conference.name %>
           <% end %>
     <% end %>
<% end %>

**Comment by ballardaf** [comment]
The conference can go between "Conference" and the login button. My idea would be to query the database in the application controller and then set the fair name that way. I'm not entirely sure, so ask corey if there's a really easy way to do that.

**Comment by ballardaf** [comment]
pushed to production
